name: Release Pull Request

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version(v1.0.0)'
        required: true

jobs:
  release:
    name: Create Release Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch only one branch to release
          fetch-depth: 100

      - name: Create Release Pull Request
        uses: modern-js-dev/actions@main
        with:
          # this expects you to have a script called release which does a build for your packages and calls changeset publish
          versionNumber: ${{ github.event.inputs.version }}
          type: 'pull request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref }}
